# Generated by Django 5.1.5 on 2025-01-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challenge_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchallenge',
            name='points',
        ),
    ]
